# Developed by Eng Mouaz M AlShahmeh
name: brick_breaker_flutter_game
description: Developed by Eng Mouaz M. Al-Shahmeh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  shared_preferences: ^2.0.9
  get_it: ^7.2.0
  audioplayers: ^0.20.1
  flutter_share: ^2.0.0
  cupertino_icons: ^1.0.2
  rate_my_app: ^1.1.1+1
  animated_text_kit: ^4.2.1
  avatar_glow: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/levels/
    - assets/audio/
  fonts:
    - family: Debug
      fonts:
        - asset: assets/fonts/debug.otf
    - family: Blaka
      fonts:
        - asset: assets/fonts/blaka.ttf
